### ISSUE TITLE
Add sequential search code to the searches directory

### ISSUE THREAD

**Issue by Nitin-Pilkhwal** [Shikha-code36/Competitive-Python#2]
I noticed that the searches directory of this repository does not currently contain a sequential search implementation. I would like to add this functionality by creating a new module in the searches directory. The module would contain a function called sequential_search that takes an input list and target value and returns the index of the target value in the list, or -1 if the target value is not found.
Please assign this issue to me and then I will create a new branch to add this code, and create a pull request once it is completed. 
Thank you for considering this contribution.

**Comment by Shikha-code36** [comment]
Sure we can add this functionality . You can create a PR for the same if you have worked on, we will merge it and release it in new version .

**Comment by Nitin-Pilkhwal** [comment]
Okay Shikha I make the module and will send you a pull request
