### ISSUE TITLE
Update error message in linear search function

### ISSUE THREAD

**Issue by Nitin-Pilkhwal** [Shikha-code36/Competitive-Python#3]
The current error message in the linear_search function says "An error occurred during binary search". This is misleading because the function is actually a linear search, not a binary search. The error message should be updated to reflect this.

Proposed Change:
Update the error message in the linear_search function from:
`logging.exception("An error occurred during binary search: %s", e)`

To :
`logging.exception("An error occurred during linear search: %s", e)`

This will help users better understand the nature of the error and what function it occurred in.

I already made a pull request on this issue - https://github.com/Shikha-code36/Competitive-Python/pull/1

Thank you for considering my contribution. 🤍

**Comment by Shikha-code36** [comment]
Merged Thankyou for pointing out
